dist: xenial
language: ruby
gemfile: ci/Gemfile
env:
  - ACTIVE_SUPPORT=true
  - NO_ACTIVE_SUPPORT=true
  - ACTIVE_SUPPORT=true FARADAY_VERSION=0.17
  - NO_ACTIVE_SUPPORT=true FARADAY_VERSION=0.17
  # Faraday < 0.9.0 doesn't support the new error class format
  - ACTIVE_SUPPORT=true FARADAY_VERSION=0.8.0
  - NO_ACTIVE_SUPPORT=true FARADAY_VERSION=0.8.0
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
before_install:
   - gem install bundler
